"""The published results document on a desktop, a tablet and a phone.

Reported from a phone: the results table cut off mid-column, the banner filling
a third of the screen before anything worth reading, and a footer telling the
reader to save the file and upload it to the club website — which they are, in
all likelihood, already looking at.

Measured at 1440, 820 and 390, before:

    desktop  overflow 0    banner 119px (13%)
    tablet   overflow 62   banner 119px (10%)
    phone    overflow 438  banner 249px (30%)   first table below the fold

The phone number is the reported fault. ``.racetable`` is 804px wide — as wide
as its columns need, and none of them can go without dropping something a
competitor came to read — and it had no scroll container, so it took the whole
document sideways with it: headings, banner and all. A table that scrolls is
normal; a page that scrolls is broken.

The 62px on the tablet was a different thing wearing the same clothes. Not a
table at all: the sponsor strip only got ``flex-wrap`` below 700px, so between
700 and about 1100 the last logo simply hung over the edge.

After: **zero horizontal overflow at all three widths.**
"""
from __future__ import annotations

import pathlib

TPL = (pathlib.Path(__file__).resolve().parent.parent
       / "templates" / "series_publish.html").read_text(encoding="utf-8")


class TestTablesScrollNotThePage:
    def test_there_is_a_scroll_wrapper(self):
        assert ".tablewrap" in TPL
        assert "overflow-x: auto" in TPL.split(".tablewrap {")[1].split("}")[0]

    def test_the_series_table_is_wrapped(self):
        head = TPL.split('<table class="summarytable">')[0]
        assert head.rstrip().endswith('<div class="tablewrap">'), head[-120:]

    def test_the_race_table_is_wrapped(self):
        head = TPL.split('<table class="racetable">')[0]
        assert head.rstrip().endswith('<div class="tablewrap">'), head[-120:]

    def test_both_wrappers_are_closed(self):
        """An unclosed one would put the rest of the document inside a scroll
        box, which is a worse fault than the one being fixed."""
        assert TPL.count('<div class="tablewrap">') == 2
        assert TPL.count("</table>\n        </div>") + TPL.count("</table>\n      </div>") == 2

    def test_a_cut_off_table_says_it_can_be_pushed(self):
        """Without a cue, a table clipped mid-column reads as a broken page --
        which is how this was reported. Shadows on whichever edge has more
        table beyond it, in CSS, with nothing to keep in sync."""
        block = TPL.split(".tablewrap, .toolbar {")[1].split("}")[0]
        assert "radial-gradient" in block
        assert "local" in block and "scroll" in block


class TestTheBannerLeavesRoomForTheResults:
    def test_the_sponsor_strip_wraps_at_every_width(self):
        """Seven logos at up to 160px do not fit an 820px tablet, and without
        this the last one hung 62px past the edge."""
        base = TPL.split(".publish-sponsor-strip {")[1].split("}")[0]
        assert "flex-wrap: wrap" in base

    def test_a_phone_gets_a_smaller_banner(self):
        phone = TPL.split("@media (max-width: 700px) {")[1].split("@media")[0]
        assert "max-height: 32px" in phone       # sponsor logos
        assert "max-height: 52px" in phone       # club logo

    def test_and_less_body_padding(self):
        phone = TPL.split("@media (max-width: 700px) {")[1].split("@media")[0]
        assert "body { padding: 12px; }" in phone


class TestTheFooter:
    @staticmethod
    def _note():
        """The footer as it renders. Asserting against the whole template would
        match the Jinja comment that explains why the old wording went."""
        return TPL.split('<p class="print-note">')[1].split("</p>")[0]

    def test_it_no_longer_tells_the_reader_to_upload_the_file(self):
        """The app publishes it now, and most people reading it are on the club
        website, where being told to upload it there is a puzzle."""
        note = self._note()
        assert "Save this HTML file" not in note
        assert "upload it to the club website" not in note

    def test_it_still_says_where_it_came_from_and_that_it_is_provisional(self):
        note = self._note()
        assert "Generated by Pwllheli Race Officer" in note
        assert "provisional" in note
